services:
  unit-tests:
    build: .
    mem_limit: 1g 
    container_name: unit-tests
    command: >
      sh -c "node --experimental-vm-modules node_modules/jest/bin/jest.js
      tests/Unitarias --runInBand --verbose --reporters=default
      --reporters=jest-junit"
    volumes:
      - .:/app
      - ./reports:/app/reports
    environment:
      - JEST_JUNIT_OUTPUT_DIR=./reports/unit
      - JEST_JUNIT_OUTPUT_NAME=unit-report.xml

  integration-tests:
    build: .
    mem_limit: 2g
    container_name: integration-tests
    # 👇 Ejecutar como root evita el error de permisos al acceder al socket de Docker
    user: root
    depends_on:
      - unit-tests
    command: >
      sh -c "npx jest tests/Integracion --verbose --runInBand --reporters=default
      --reporters=jest-junit"
    volumes:
      # Código y reportes
      - .:/app
      - ./reports:/app/reports

      # 👇 Monta el socket del Docker host (clave para Testcontainers)
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JEST_JUNIT_OUTPUT_DIR=./reports/integration
      - JEST_JUNIT_OUTPUT_NAME=integration-report.xml

      # 👇 Hace explícito el host de Docker
      - DOCKER_HOST=unix:///var/run/docker.sock

      # 👇 Opcional: permite a Testcontainers omitir comprobaciones de TLS
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
      - TESTCONTAINERS_RYUK_DISABLED=true
      - script: |
         docker-compose down -v
        displayName: 'Clean up test containers'

