services:
  unit-tests:
    build: .
    container_name: unit-tests
    # NO ejecutar tests autom치ticamente al iniciar - el pipeline lo har치
    command: tail -f /dev/null
    volumes:
      - .:/app:cached
      - /app/node_modules
      - ./reports:/app/reports
    environment:
      - JEST_JUNIT_OUTPUT_DIR=./reports/unit
      - JEST_JUNIT_OUTPUT_NAME=unit-report.xml
      - NODE_OPTIONS=--max-old-space-size=2048
    mem_limit: 3g
    memswap_limit: 3g
    
  integration-tests:
    build: .
    container_name: integration-tests
    depends_on:
      - unit-tests
    # NO ejecutar tests autom치ticamente al iniciar - el pipeline lo har치
    command: tail -f /dev/null
    volumes:
      - .:/app:cached
      - /app/node_modules
      - ./reports:/app/reports
      - /var/run/docker.sock:/var/run/docker.sock  # Para Testcontainers
    environment:
      - JEST_JUNIT_OUTPUT_DIR=./reports/integration
      - JEST_JUNIT_OUTPUT_NAME=integration-report.xml
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
      - DOCKER_HOST=tcp://host.docker.internal:2375
      - TESTCONTAINERS_RYUK_DISABLED=true
      - TESTCONTAINERS_CHECKS_DISABLE=true
      - NODE_OPTIONS=--max-old-space-size=3072
    mem_limit: 4g
    memswap_limit: 4g