###
@BASE_URL = http://localhost:80
@AUTH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMiIsImlhdCI6MTc1MDc5NzE3MywiZXhwIjoxNzUwODMzMTczfQ.B_8Uo8zcbNrYDMlaEgIHRZk_apxrN4aWlmH1JJeAZhQ

# 
# Rutas del archivo misc.js
# 

###
GET {{ BASE_URL }}/personas/Listar HTTP/1.1
Content-Type: application/json


###
GET {{ BASE_URL }}/personas/ObtenerPersona/12 HTTP/1.1
Content-Type: application/json


###
POST  {{ BASE_URL }}/personas/Agregar HTTP/1.1
Content-Type: application/json

 {
        "Identificacion":155821845336,
         "Nombre":"jesus",
          "Contrasenna":"123",
         "Telefono":"8762",
         "Correo":"sdfewer" ,
         "Perfil": "Administrador"
    }

###
PUT  {{ BASE_URL }}/personas/Actualizar HTTP/1.1
Content-Type: application/json

 {
      
        "Identificacion":12,
         "Nombre":"jesussssssssssssf",
          "Contrasenna":"123",
         "Telefono":"8762",
         "Correo":"sdfewer" 
    }


###
DELETE  {{ BASE_URL }}/personas/Eliminar/13 HTTP/1.1
Content-Type: application/json


###
POST  {{ BASE_URL }}/personas/ValidarSesion HTTP/1.1
Content-Type: application/json

 {
        "Identificacion":12,
          "Contrasenna":"123"
    }