###
@BASE_URL = http://localhost:80
@AUTH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGRiMzQ2NzZjNzk2OGE3YTE5YjQzMCIsInJvbCI6InVuZGVmaW5lZCIsImlkZW50aWZpY2FjaW9uIjoiMTU1ODIxODQ1MzM2Iiwibm9tYnJlIjoiSmVzdXMgQWN0dWFsaXphY2nDs24iLCJpYXQiOjE3NjA2NzY3NTQsImV4cCI6MTc2MDY4MDM1NH0.xS9fYVbtv6hltAaSDdR_jtvBxwy3orSTfiOLB21tPdw

# 
# Rutas de Personas
# 

###
GET {{ BASE_URL }}/personas/Listar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ AUTH_TOKEN }}


###
GET {{ BASE_URL }}/personas/ObtenerPersona/155821845336 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ AUTH_TOKEN }}


###
POST  {{ BASE_URL }}/personas/Agregar HTTP/1.1
Content-Type: application/json

 {
        "Identificacion":303030303,
         "Nombre":"usuario de prueba",
          "Contrasenna":"123456789",
         "Telefono":"8762",
         "Correo":"sdfewer" ,
         "Perfil": "Votante"
    }

###
PUT  {{ BASE_URL }}/personas/Actualizar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ AUTH_TOKEN }}

 {
      
    "Identificacion": "155821845336",
    "Nombre": "Jesus Actualización",
    "Contrasenna": "123456789",
    "Telefono": "87628899",
    "Correo": "prueb2025a@gmail.com",
    "Perfil": "Administrador"
    }


###
DELETE  {{ BASE_URL }}/personas/Eliminar/13 HTTP/1.1
Content-Type: application/json


###
POST  {{ BASE_URL }}/personas/ValidarSesion HTTP/1.1
Content-Type: application/json

 {
        "Identificacion":101010101,
          "Contrasenna":"123456789"
    }

# 
# Rutas de Sedes
# 

###
GET {{ BASE_URL }}/sedes/Listar HTTP/1.1
Content-Type: application/json

###
GET {{ BASE_URL }}/sedes/ObtenerSede/1 HTTP/1.1
Content-Type: application/json

###
POST {{ BASE_URL }}/sedes/Agregar HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Sede Central UTN"
}

###
PUT {{ BASE_URL }}/sedes/Actualizar/1 HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Sede Central UTN Actualizada"
}

###
DELETE {{ BASE_URL }}/sedes/Eliminar/1 HTTP/1.1
Content-Type: application/json

# 
# Rutas de Elecciones
# 

###
GET {{ BASE_URL }}/elecciones/Listar HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ AUTH_TOKEN }}

###
GET {{ BASE_URL }}/elecciones/Vigentes HTTP/1.1
Content-Type: application/json

###
GET {{ BASE_URL }}/elecciones/ObtenerEleccion/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json

###
POST {{ BASE_URL }}/elecciones/Agregar HTTP/1.1
Content-Type: application/json
Authorization: AUTH_TOKEN 

{
    "Nombre": "Elecciones Estudiantiles 2025",
    "SedeId": 1,
    "PerfilId": 81,
    "FechaInicio": "2025-10-05T08:00:00.000Z",
    "FechaFin": "2025-10-15T18:00:00.000Z"
}

###
PUT {{ BASE_URL }}/elecciones/Actualizar/68e348611a7a4aee788adeb7 HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Elecciones Estudiantiles 2025 - Segunda Vuelta",
    "SedeId": 1,
    "PerfilId": 1,
    "FechaInicio": "2025-10-12T08:00:00.000Z",
    "FechaFin": "2025-10-12T18:00:00.000Z"
}

### Activate an election
PUT {{ BASE_URL }}/elecciones/Abrir/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json

### Deactivate an election
PUT {{ BASE_URL }}/elecciones/Cerrar/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json

###
DELETE {{ BASE_URL }}/elecciones/Eliminar/68e496f112a0316498d3e2ad HTTP/1.1
Content-Type: application/json

###
POST {{ BASE_URL }}/elecciones/AgregarCandidato/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json

{
    "NombreCandidato": "Marcos Sólis"
}

###
DELETE {{ BASE_URL }}/elecciones/EliminarCandidato/68e496f112a0316498d3e2ad/Juan%20Pérez HTTP/1.1
Content-Type: application/json

# 
# Rutas de Candidatos
# 

###
GET {{ BASE_URL }}/candidatos/Listar HTTP/1.1
Content-Type: application/json

###
POST {{ BASE_URL }}/candidatos/Agregar HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Rafael Pérez",
    "Partido": "Partido Democrático",
    "PerfilId": 2
}

###
PUT {{ BASE_URL }}/candidatos/Actualizar HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Juan Pérez",
    "Partido": "Partido Democrático Actualizado",
    "PerfilId": 1
}

###
DELETE {{ BASE_URL }}/candidatos/Eliminar/Juan%20Pérez HTTP/1.1
Content-Type: application/json

# 
# Rutas de Perfiles de Elecciones
# 

###
GET {{ BASE_URL }}/perfiles/Listar HTTP/1.1
Content-Type: application/json

###
GET {{ BASE_URL }}/perfiles/ObtenerPerfil/81 HTTP/1.1
Content-Type: application/json

###
POST {{ BASE_URL }}/perfiles/Agregar HTTP/1.1
Content-Type: application/json

{
    "Descripcion": "secretario Estudiantil"
}

###
PUT {{ BASE_URL }}/perfiles/Actualizar/1 HTTP/1.1
Content-Type: application/json

{
    "Descripcion": "Presidente del Consejo Estudiantil"
}

###
DELETE {{ BASE_URL }}/perfiles/Eliminar/1 HTTP/1.1
Content-Type: application/json

# 
# Rutas de Candidatos
# 

###
GET {{ BASE_URL }}/candidatos/Listar HTTP/1.1
Content-Type: application/json

###
GET {{ BASE_URL }}/candidatos/ObtenerCandidato/Juan%20Pérez HTTP/1.1
Content-Type: application/json

###
POST {{ BASE_URL }}/candidatos/Agregar HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Juan Pérez",
    "Partido": "Partido Estudiantil",
    "PerfilId": 1
}

###
PUT {{ BASE_URL }}/candidatos/Actualizar/Juan%20Pérez HTTP/1.1
Content-Type: application/json

{
    "Partido": "Partido Estudiantil Renovado",
    "PerfilId": 1
}

###
DELETE {{ BASE_URL }}/candidatos/Eliminar/Juan%20Pérez HTTP/1.1
Content-Type: application/json

# 
# Rutas de Votos
# 

###
# Registrar un voto
POST {{ BASE_URL }}/votos/Registrar HTTP/1.1
Content-Type: application/json

{
  "Identificacion": "155821845336",
  "EleccionId": "68e6e46c7ee7c43e82142388",
  "CandidatoId": "68e4991ea602dae0834210fe"
}

###
# Consultar votos por elección
GET {{ BASE_URL }}/votos/PorEleccion/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json

###
# Consultar votos por elección
GET {{ BASE_URL }}/votos/ParticipantesPorEleccion/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json

###
# Consultar votos por elección
GET {{ BASE_URL }}/votos/ParticipantesPorEleccion2/68e6e46c7ee7c43e82142388 HTTP/1.1
Content-Type: application/json



###
# Consultar votos por persona
GET {{ BASE_URL }}/votos/PorPersona/155821845336 HTTP/1.1
Content-Type: application/json